name: Deploy to Firebase Hosting

on:
  pull_request_target:
    branches:
      - master  # main 브랜치로의 push에 반응하도록 설정

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # 가장 최신의 Ubuntu 버전에서 실행

    steps:
    - uses: actions/checkout@v2  # 코드 체크아웃

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    - name: Build Web
      run: |
        flutter --version
        flutter pub get
        flutter build web  # Flutter 웹 앱 빌드

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0.7.1
      with:
        projectId: ygo-blog-client  # 여기에 Firebase 프로젝트 ID를 입력하세요.
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # GitHub Secrets에서 설정한 이름을 사용하세요.
        expires: 7d  # 선택 사항: 배포가 만료되는 시간입니다.
        entryPoint: .  # 선택 사항: Firebase 프로젝트의 루트 디렉토리입니다.
        firebaseToolsVersion: latest  # 선택 사항: 사용할 Firebase Tools의 버전입니다.
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Firebase 토큰

